# Generated by Django 6.0.3 on 2026-03-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalyzer', '0003_jobmatchanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
