# Generated by Django 6.0.3 on 2026-03-24 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalyzer', '0002_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('match_score', models.IntegerField(default=0)),
                ('missing_skills', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('Resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeAnalyzer.resume')),
            ],
        ),
    ]
