# Generated by Django 6.0.3 on 2026-03-31 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeAnalyzer', '0004_alter_resume_uploaded_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmatchanalysis',
            old_name='Resume',
            new_name='resume',
        ),
    ]
